FROM nginx

COPY buildkit.conf /etc/nginx/conf.d/buildkit.conf

COPY fastcgi.conf /etc/nginx/fastcgi.conf

COPY index.html /usr/share/nginx/html/index.html

COPY index.php /usr/share/nginx/html/index.php
