#!/bin/sh
set -e

# Set remote host for xdebug
export XDEBUG_REMOTE_HOST=`/sbin/ip route|awk '/default/ { print $3 }'`

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
