#!/bin/sh
set -e

# xdebug setup
CONTAINER_IP=`/sbin/ip route|awk '/default/ { print $3 }'`
cat << EOF > /usr/local/etc/php/conf.d/debug.ini
zend_extension=xdebug.so

xdebug.mode=develop,debug
xdebug.client_host=${CONTAINER_IP}
xdebug.start_with_request=yes
xdebug.log_level=0
xdebug.cli_color = 1
xdebug.var_display_max_depth = 2
xdebug.var_display_max_children = 128
xdebug.var_display_max_data = 128

max_execution_time=600
EOF

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
